name: EnhancedArmors
author: EndegamerHUN
version: 0.0.1
api-version: 1.14
main: io.github.endergamerhun.enhancedarmors.EnhancedArmors

commands:
  enhancedarmors:
    description: WIP
    permission: enhancedarmors.command